//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Gareev_Danil_Edikovich.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchTeam
    {
        public int MatchTeamID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string TimeStamp { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Team { get; set; }
    }
}
