//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Gareev_Danil_Edikovich.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizer
    {
        public int OrganizerID { get; set; }
        public string Initial { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
