//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Gareev_Danil_Edikovich.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTeam
    {
        public int PlayerTeamID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Role Role { get; set; }
        public virtual Team Team { get; set; }
    }
}
