//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Gareev_Danil_Edikovich.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMatch
    {
        public int PlayerMatchID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string Timestamp { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
